### PR TITLE
Molviewer Toolbar

### PR DESCRIPTION
**Pull request by justinmc**
I was unable to include the main molviewer CSS because it would shrink the viewer in weird ways.  Andrew kindly made me a tiny css file for the headless viewer only that allows us to show the missing toolbar icons.

In the future, this css will ideally be a part of the molviewer package instead of its own css file in this repo.

screen shot 2017-02-24 at 3 06 36 pm

### CODE REVIEW

**Comment by justinmc** [comment]
@avirshup Whoops forgot to add that file to the commit :)

**Comment by avirshup** [comment]
@justinmc I'm actually getting the bug from #179 here, so I'm not able to see the controls :(

**Comment by justinmc** [comment]
@avirshup Ah true, this will have to wait until we've got the molviewer thing fixed.

**Comment by justinmc** [comment]
@avirshup The molviewer bug should be gone now, so this should be reviewable.

**Comment by avirshup** [comment]
@justinmc - ok, got this up and running with tirrenu-1.3.5! The toolbar's working well. However, the protein displays in stick mode now:
image
But I'll try some newer branches and see if the problem manifests there too

**Comment by justinmc** [comment]
@avirshup I put everything in stick mode in https://github.com/Autodesk/molecular-simulation-tools/pull/155 due to the animation API needing to be in stick mode.  Maybe I can do something fancier and only show stick mode on the results step if that's better.

**Comment by avirshup** [comment]
Ohhh, right, I remember that. In which case - this looks good!

**Comment by justinmc** [comment]
Ok cool.  We can always do another PR to sort out the stick stuff.

**Pull request merged**
